#!/usr/bin/env python3
"""
Nexus AI - Flask Backend Server (Local Only)
Provides /ask, /health, /scrape_products endpoints on port 5001.
Connects to Ollama (Mistral 7B) running locally — no web search, no Playwright.
"""

import json
import re
import os
from datetime import datetime

import requests
from flask import Flask, request, jsonify
from flask_cors import CORS

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/chat")
MODEL = os.environ.get("OLLAMA_MODEL", "mistral")  # Mistral 7B via Ollama

app = Flask(__name__)
CORS(app)  # Allow cross-origin requests from the frontend


# ---------------------------------------------------------------------------
# Helper: call Ollama LLM
# ---------------------------------------------------------------------------
def call_ollama(prompt: str, timeout: int = 120) -> str:
    """Send a prompt to Ollama and return the assistant text."""
    payload = {
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
    }
    try:
        r = requests.post(OLLAMA_URL, json=payload, timeout=timeout)
        r.raise_for_status()
        body = r.json()
        text = body.get("message", {}).get("content", "")
        if not text and "choices" in body:
            text = "".join(
                c.get("message", {}).get("content", "") for c in body["choices"]
            )
        return text.strip()
    except requests.exceptions.ConnectionError:
        return "[Error] Cannot connect to Ollama. Make sure 'ollama serve' is running on port 11434."
    except Exception as e:
        return f"[Error] LLM call failed: {e}"


# ---------------------------------------------------------------------------
# Route: /health
# ---------------------------------------------------------------------------
@app.route("/health", methods=["GET"])
def health():
    """Health check endpoint."""
    ollama_ok = False
    try:
        r = requests.get("http://localhost:11434/api/tags", timeout=3)
        ollama_ok = r.status_code == 200
    except Exception:
        pass

    return jsonify({
        "status": "ok",
        "ollama": "connected" if ollama_ok else "disconnected",
        "model": MODEL,
        "timestamp": datetime.now().isoformat(),
    })


# ---------------------------------------------------------------------------
# Route: /ask  (main chat endpoint)
# ---------------------------------------------------------------------------
@app.route("/ask", methods=["POST"])
def ask():
    """
    Main chat endpoint.
    Expects JSON: { "question": "..." }
    Returns JSON: { "answer": "...", "sources": [...] }
    """
    data = request.get_json(force=True)
    question = data.get("question", "").strip()

    if not question:
        return jsonify({"error": "No question provided"}), 400

    print(f"\n{'='*60}")
    print(f"📝 Question: {question}")
    print(f"{'='*60}")

    prompt = (
        "You are Nexus AI, a knowledgeable and helpful assistant. "
        "Answer the user's question accurately and in a well-formatted way. "
        "Use your own knowledge to provide the best answer. "
        "Format your response with markdown for readability.\n\n"
        f"User's question: {question}\n\n"
        "Provide a comprehensive, accurate answer:"
    )

    # Call Mistral via Ollama
    print("🧠 Asking Mistral 7B...")
    answer = call_ollama(prompt, timeout=120)
    print(f"✅ Got response ({len(answer)} chars)")

    return jsonify({
        "answer": answer,
        "sources": [],
        "model": MODEL,
        "timestamp": datetime.now().isoformat(),
    })


# ---------------------------------------------------------------------------
# Route: /scrape_products  (data query — local LLM only)
# ---------------------------------------------------------------------------
@app.route("/scrape_products", methods=["POST"])
def scrape_products():
    """
    Data query endpoint (local only, no web scraping).
    Expects JSON: { "query": "...", "limit": 20, "batch_size": 10 }
    Returns JSON with batches of results generated by the LLM.
    """
    data = request.get_json(force=True)
    query = data.get("query", "").strip()
    limit = int(data.get("limit", 20))
    batch_size = int(data.get("batch_size", 10))

    if not query:
        return jsonify({"success": False, "error": "No query provided"}), 400

    print(f"\n{'='*60}")
    print(f"� Data Query: {query}")
    print(f"{'='*60}")

    # Ask Mistral to generate structured data from its knowledge
    extract_prompt = (
        "You are a data assistant. Based on your knowledge, "
        "provide relevant items for the user's query.\n\n"
        f"User query: {query}\n\n"
        "Return a JSON array of objects. Each object should have:\n"
        '- "title": string (name of the item)\n'
        '- "description": string (brief description)\n'
        '- "price": string or null (if applicable)\n'
        '- "url": null\n'
        '- "source": "Mistral 7B (Local)"\n\n'
        f"Return up to {min(limit, 20)} items. Return ONLY valid JSON array, no extra text."
    )

    print("🧠 Asking Mistral 7B...")
    raw_response = call_ollama(extract_prompt, timeout=120)
    print(f"✅ Got response ({len(raw_response)} chars)")

    all_items = []

    # Try to parse JSON from LLM response
    try:
        cleaned = re.sub(r"^```json\s*|\s*```$", "", raw_response.strip(), flags=re.DOTALL)
        items = json.loads(cleaned)
        if isinstance(items, list):
            all_items = items
        elif isinstance(items, dict) and "items" in items:
            all_items = items["items"]
    except json.JSONDecodeError:
        # If JSON parsing fails, return the raw text as a single item
        all_items = [{
            "title": query,
            "description": raw_response[:500],
            "price": None,
            "url": None,
            "source": "Mistral 7B (Local)",
        }]

    # Split into batches
    batches = []
    for i in range(0, len(all_items), batch_size):
        batch = all_items[i : i + batch_size]
        batches.append({
            "batch_number": (i // batch_size) + 1,
            "items": batch,
            "count": len(batch),
        })

    return jsonify({
        "success": True,
        "query": query,
        "total_items": len(all_items),
        "batches": batches,
        "model": MODEL,
        "timestamp": datetime.now().isoformat(),
    })


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("  🚀 Nexus AI Backend Server (Local Only)")
    print("=" * 60)
    print(f"  Model   : {MODEL}")
    print(f"  Ollama  : {OLLAMA_URL}")
    print(f"  Mode    : Local only (no web search)")
    print(f"  Server  : http://localhost:5001")
    print("=" * 60 + "\n")

    app.run(host="0.0.0.0", port=5001, debug=False)
